addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"        % "0.12.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.10.0")
addSbtPlugin("org.typelevel"     % "sbt-tpolecat"        % "0.5.2")
addSbtPlugin("com.github.sbt"    % "sbt-ci-release"      % "1.6.1")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.10.4")
