addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.5.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.10.4")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"          % "5.7.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.3.3")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"      % "1.5.11")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager" % "1.9.12")
